"""Small self-contained API explorer; no CDN assets or external requests."""
import html,json
from fastapi.responses import HTMLResponse

def page(schema):
    items=[]
    samples={'/api/sea-ice/forecast':{'horizon':24},'/api/risk/inspect':{'x':-270,'y':2640,'horizon':24},'/api/copilot':{'question':'Why this route?'},'/api/data/import':{'rows':[{'latitude':-67,'longitude':76,'concentration':.3,'observed_at':'2026-02-15T06:00:00Z','source':'SYNTHETIC API EXAMPLE'}]}}
    for path,methods in schema['paths'].items():
        if not path.startswith('/api/'):continue
        for method,meta in methods.items():
            if method not in ['get','post']:continue
            sample=samples.get(path,{})
            items.append(f'''<details><summary><span class="method {method}">{method.upper()}</span><code>{html.escape(path)}</code><small>{html.escape(meta.get('summary',''))}</small></summary><div class="entry"><p>{html.escape(meta.get('description','Local research/demo endpoint. No live-data or navigation-safety claim.'))}</p>{'<label>JSON request body<textarea>'+html.escape(json.dumps(sample,indent=2))+'</textarea></label>' if method=='post' else ''}<button data-method="{method}" data-path="{html.escape(path)}">Send local request</button><pre aria-live="polite">Response will appear here.</pre></div></details>''')
    return HTMLResponse('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>POLAR PULSE | Local API explorer</title><style>
    :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07111d;color:#e9f3f8;font:14px/1.55 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:35px 22px}a{color:#8be0ed}h1{font-size:35px;margin:10px 0}h1 span{font-weight:350;color:#87ddeb}.eyebrow{color:#82b5c9;font-size:11px;letter-spacing:2px}.note{background:#16282e;border:1px solid #315057;border-radius:9px;padding:17px;color:#accbd3;margin:20px 0}details{background:#0d2030;border:1px solid #294454;border-radius:8px;margin:10px 0}summary{display:flex;align-items:center;gap:13px;padding:14px;cursor:pointer;flex-wrap:wrap}.method{display:inline-block;padding:3px 8px;border-radius:4px;background:#12443e;color:#93ebcd;font:bold 11px system-ui}.method.post{background:#344027;color:#d9e8a3}summary code{font-size:13px;color:#d6ebf4}summary small{margin-left:auto;color:#86a7b7}.entry{padding:0 18px 18px}textarea,pre{font:12px/1.5 Consolas,monospace;width:100%;padding:14px;background:#06131d;color:#d4ecf7;border:1px solid #294653;border-radius:6px;white-space:pre-wrap;overflow-wrap:anywhere}textarea{display:block;min-height:150px;margin:7px 0 13px}button{background:#87ddeb;color:#092230;padding:9px 14px;border:0;border-radius:6px;font:600 12px system-ui;cursor:pointer}pre{max-height:440px;overflow:auto}label{color:#93b3c4;font-size:12px}footer{font-size:12px;color:#7795a8;margin:25px 0}</style></head><body><main><span class="eyebrow">POLAR PULSE / DEVELOPER REFERENCE</span><h1>One local API.<br><span>No external dependencies.</span></h1><p><a href="/">Back to mission control</a> &nbsp; / &nbsp; <a href="/openapi.json">Raw OpenAPI schema</a></p><div class="note">These endpoints operate on a synthetic research scenario. The server is local and unauthenticated. Do not expose it publicly or use its outputs for real navigation. Requests below go only to this same-origin application.</div>'''+''.join(items)+'''<details><summary>Full schema definitions</summary><div class="entry"><pre>'''+html.escape(json.dumps(schema.get('components',{}),indent=2))+'''</pre></div></details><footer>POLAR PULSE 1.0 / Offline API explorer / Research demonstration only.</footer></main><script>document.addEventListener('click',async e=>{const b=e.target.closest('button[data-path]');if(!b)return;const panel=b.closest('.entry'),out=panel.querySelector('pre'),method=b.dataset.method.toUpperCase();b.disabled=true;out.textContent='Requesting local engine...';try{let body;if(method==='POST')body=JSON.stringify(JSON.parse(panel.querySelector('textarea').value));const r=await fetch(b.dataset.path,{method,headers:method==='POST'?{'Content-Type':'application/json'}:undefined,body});const text=await r.text();let result;try{result=JSON.stringify(JSON.parse(text),null,2);}catch{result=text;}out.textContent='HTTP '+r.status+'\\n'+result;}catch(err){out.textContent=String(err);}finally{b.disabled=false;}});</script></body></html>''')
